// Offline: app shell cached first (build plan section 1).
// Bump CACHE on every content or code change. Older gg- caches are deleted on activate;
// caches of other apps on the same origin are never touched.
const CACHE = 'gg-v1-20261005nf';
const ASSETS = [
  './',
  './audio/audio-manifest.json',
  './audio/c-done.mp3',
  './audio/c-great.mp3',
  './audio/c-level.mp3',
  './audio/c-new.mp3',
  './audio/c-yay1.mp3',
  './audio/c-yay2.mp3',
  './audio/fx-boing.mp3',
  './audio/fx-chime.mp3',
  './audio/fx-confetti.mp3',
  './audio/fx-giggle.mp3',
  './audio/fx-meow.mp3',
  './audio/fx-mmm.mp3',
  './audio/fx-pop.mp3',
  './audio/fx-sneeze.mp3',
  './audio/fx-sniff.mp3',
  './audio/fx-toot.mp3',
  './audio/fx-woof.mp3',
  './audio/fx-yip.mp3',
  './audio/fx-zoom.mp3',
  './audio/h-add.mp3',
  './audio/h-book.mp3',
  './audio/h-count.mp3',
  './audio/h-letters.mp3',
  './audio/h-pattern.mp3',
  './audio/h-says.mp3',
  './audio/h-stories.mp3',
  './audio/hi-blackDog.mp3',
  './audio/hi-bunny.mp3',
  './audio/hi-bunny2.mp3',
  './audio/hi-chocolateDog.mp3',
  './audio/hi-friendBerry.mp3',
  './audio/hi-friendCounter.mp3',
  './audio/hi-friendDino.mp3',
  './audio/hi-friendSea.mp3',
  './audio/hi-friendSilly.mp3',
  './audio/hi-gingerDog.mp3',
  './audio/hi-kitty.mp3',
  './audio/hi-puppy.mp3',
  './audio/hi-yellowDog.mp3',
  './audio/n-1.mp3',
  './audio/n-10.mp3',
  './audio/n-11.mp3',
  './audio/n-12.mp3',
  './audio/n-13.mp3',
  './audio/n-14.mp3',
  './audio/n-15.mp3',
  './audio/n-16.mp3',
  './audio/n-17.mp3',
  './audio/n-18.mp3',
  './audio/n-19.mp3',
  './audio/n-2.mp3',
  './audio/n-20.mp3',
  './audio/n-3.mp3',
  './audio/n-4.mp3',
  './audio/n-5.mp3',
  './audio/n-6.mp3',
  './audio/n-7.mp3',
  './audio/n-8.mp3',
  './audio/n-9.mp3',
  './audio/p-all.mp3',
  './audio/p-box.mp3',
  './audio/p-count.mp3',
  './audio/p-find.mp3',
  './audio/p-like.mp3',
  './audio/p-next.mp3',
  './audio/ps-balance.mp3',
  './audio/ps-bear.mp3',
  './audio/ps-bunny.mp3',
  './audio/ps-c-clap.mp3',
  './audio/ps-c-hop.mp3',
  './audio/ps-c-jump.mp3',
  './audio/ps-c-spin.mp3',
  './audio/ps-c-stomp.mp3',
  './audio/ps-calm.mp3',
  './audio/ps-chick.mp3',
  './audio/ps-clap.mp3',
  './audio/ps-dino.mp3',
  './audio/ps-freeze.mp3',
  './audio/ps-frog.mp3',
  './audio/ps-lead.mp3',
  './audio/ps-nose.mp3',
  './audio/ps-reach.mp3',
  './audio/ps-roar.mp3',
  './audio/ps-silly.mp3',
  './audio/ps-spin.mp3',
  './audio/ps-star.mp3',
  './audio/ps-then.mp3',
  './audio/ps-times.mp3',
  './audio/ps-toes.mp3',
  './audio/ps-tuck.mp3',
  './audio/ps-wiggle.mp3',
  './audio/s-ark-1.mp3',
  './audio/s-ark-2.mp3',
  './audio/s-ark-3.mp3',
  './audio/s-ark-4.mp3',
  './audio/s-ark-5.mp3',
  './audio/s-ark-6.mp3',
  './audio/s-ark-7.mp3',
  './audio/s-ark-q.mp3',
  './audio/s-ark-yes.mp3',
  './audio/s-children-1.mp3',
  './audio/s-children-2.mp3',
  './audio/s-children-3.mp3',
  './audio/s-children-4.mp3',
  './audio/s-children-5.mp3',
  './audio/s-children-6.mp3',
  './audio/s-children-q.mp3',
  './audio/s-children-yes.mp3',
  './audio/s-creation-1.mp3',
  './audio/s-creation-2.mp3',
  './audio/s-creation-3.mp3',
  './audio/s-creation-4.mp3',
  './audio/s-creation-5.mp3',
  './audio/s-creation-6.mp3',
  './audio/s-creation-q.mp3',
  './audio/s-creation-yes.mp3',
  './audio/s-nativity-1.mp3',
  './audio/s-nativity-2.mp3',
  './audio/s-nativity-3.mp3',
  './audio/s-nativity-4.mp3',
  './audio/s-nativity-5.mp3',
  './audio/s-nativity-6.mp3',
  './audio/s-nativity-q.mp3',
  './audio/s-nativity-yes.mp3',
  './audio/s-sheep-1.mp3',
  './audio/s-sheep-2.mp3',
  './audio/s-sheep-3.mp3',
  './audio/s-sheep-4.mp3',
  './audio/s-sheep-5.mp3',
  './audio/s-sheep-6.mp3',
  './audio/s-sheep-q.mp3',
  './audio/s-sheep-yes.mp3',
  './audio/s-storm-1.mp3',
  './audio/s-storm-2.mp3',
  './audio/s-storm-3.mp3',
  './audio/s-storm-4.mp3',
  './audio/s-storm-5.mp3',
  './audio/s-storm-6.mp3',
  './audio/s-storm-q.mp3',
  './audio/s-storm-yes.mp3',
  './audio/snd-a.mp3',
  './audio/snd-b.mp3',
  './audio/snd-c.mp3',
  './audio/snd-d.mp3',
  './audio/snd-e.mp3',
  './audio/snd-f.mp3',
  './audio/snd-g.mp3',
  './audio/snd-h.mp3',
  './audio/snd-i.mp3',
  './audio/snd-j.mp3',
  './audio/snd-k.mp3',
  './audio/snd-l.mp3',
  './audio/snd-m.mp3',
  './audio/snd-n.mp3',
  './audio/snd-o.mp3',
  './audio/snd-p.mp3',
  './audio/snd-q.mp3',
  './audio/snd-r.mp3',
  './audio/snd-s.mp3',
  './audio/snd-t.mp3',
  './audio/snd-u.mp3',
  './audio/snd-v.mp3',
  './audio/snd-w.mp3',
  './audio/snd-x.mp3',
  './audio/snd-y.mp3',
  './audio/snd-z.mp3',
  './audio/t-again1.mp3',
  './audio/t-again2.mp3',
  './audio/w-and.mp3',
  './audio/w-apple.mp3',
  './audio/w-ball.mp3',
  './audio/w-cat.mp3',
  './audio/w-dog.mp3',
  './audio/w-elephant.mp3',
  './audio/w-fish.mp3',
  './audio/w-fox.mp3',
  './audio/w-goat.mp3',
  './audio/w-hat.mp3',
  './audio/w-igloo.mp3',
  './audio/w-jet.mp3',
  './audio/w-kite.mp3',
  './audio/w-lamb.mp3',
  './audio/w-moon.mp3',
  './audio/w-nest.mp3',
  './audio/w-octopus.mp3',
  './audio/w-penguin.mp3',
  './audio/w-queen.mp3',
  './audio/w-rainbow.mp3',
  './audio/w-sun.mp3',
  './audio/w-turtle.mp3',
  './audio/w-umbrella.mp3',
  './audio/w-van.mp3',
  './audio/w-whale.mp3',
  './audio/w-yo-yo.mp3',
  './audio/w-zebra.mp3',
  './css/app.css',
  './data/activities.json',
  './data/games.json',
  './data/stories.json',
  './fonts/OFL.txt',
  './fonts/gg-letters-bold.woff2',
  './fonts/gg-letters.woff2',
  './icons/apple-touch-icon.png',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon.svg',
  './index.html',
  './js/acts/add.js',
  './js/acts/count.js',
  './js/acts/index.js',
  './js/acts/letters.js',
  './js/acts/pattern.js',
  './js/art.js',
  './js/audio.js',
  './js/character.js',
  './js/dad.js',
  './js/dom.js',
  './js/engine.js',
  './js/fun.js',
  './js/games.js',
  './js/lineup.js',
  './js/lock.js',
  './js/main.js',
  './js/pets.js',
  './js/photo-core.js',
  './js/photos.js',
  './js/pics.js',
  './js/quiz.js',
  './js/reward.js',
  './js/route.js',
  './js/says.js',
  './js/screens/book.js',
  './js/screens/family.js',
  './js/screens/home.js',
  './js/screens/play.js',
  './js/screens/says.js',
  './js/screens/stories.js',
  './js/screens/story.js',
  './js/store.js',
  './js/story-art.js',
  './js/story.js',
  './js/tiles.js',
  './js/ui.js',
  './manifest.webmanifest',
];

// Install fetches every asset fresh (cache: 'reload'), never from the browser's HTTP cache, so a new
// cache name can never be filled with an older copy of a file.
self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS.map((u) => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('gg-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Same-origin GET: cache first, then network. Cross-origin requests are not handled (there are none).
// Pet photos live only in IndexedDB and are shown through blob: URLs: the worker never caches,
// stores or answers them (anything not plain http(s) is left alone), and nothing fetched is ever
// added to the cache (only the fixed ASSETS list above).
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.protocol !== 'http:' && url.protocol !== 'https:') return;
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(req).catch(() => (req.mode === 'navigate' ? caches.match('./index.html') : Response.error()));
    }),
  );
});
